# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7353aae7-0765-47da-ba1e-cb6d4838b556";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/111868c5-83d6-41bc-bec7-520fa2308d64"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
}
