# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { #device = "/dev/disk/by-uuid/ef7bd231-f5da-4f1c-aab7-a73dbbf66299";
      device = "/dev/sda2";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { #device = "/dev/disk/by-uuid/b11ebfd7-e96b-4d68-956b-e66c08cae384";
      device = "/dev/sda1";
      fsType = "ext3";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 1;
}
